spring.application.name=laranja-pay
spring.datasource.url=jdbc:postgresql://localhost:5432/Laranja-pay
spring.datasource.username=postgres
spring.datasource.password=Airton1@
spring.jpa.hibernate.ddl-auto=update
server.port=8080